#!/usr/sbin/nft -f

flush ruleset

# Подключаем переменные
include "/etc/nftables/variables.conf";

# Подключаем блоклисты
include "/etc/nftables/blocklists/ipv4.nft";
include "/etc/nftables/blocklists/ipv6.nft";

# Таблица фильтрации
table inet filter {
    include "/etc/nftables/rules/input.nft";
    include "/etc/nftables/rules/output.nft";

    chain forward {
        type filter hook forward priority filter;
    }
}