# ============================================================
# ПЕРЕМЕННЫЕ
# ============================================================

# Разрешённые порты для входящих подключений (SSH не нужен, он уже отдельно)
define ALLOWED_TCP_PORTS = {
    42603, # AmneziaWG
}

define ALLOWED_UDP_PORTS = {
    42603, # AmneziaWG
}